// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFzAHDAEqCNNgMSPxj8n7BmX8JXa7G1A',
    appId: '1:601757296711:web:8583ff0ced89e4a5bc6962',
    messagingSenderId: '601757296711',
    projectId: 'marco-ltda',
    authDomain: 'marco-ltda.firebaseapp.com',
    storageBucket: 'marco-ltda.firebasestorage.app',
    measurementId: 'G-PV664SDE9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxdWUW8eEN_IfoVGJLLvxNjjarHr4ftk',
    appId: '1:601757296711:android:034a2e51c67cdea4bc6962',
    messagingSenderId: '601757296711',
    projectId: 'marco-ltda',
    storageBucket: 'marco-ltda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiMWDlrd8ZnUSklfRB6GiypmPQE4SHuDA',
    appId: '1:601757296711:ios:7080415e11fb4557bc6962',
    messagingSenderId: '601757296711',
    projectId: 'marco-ltda',
    storageBucket: 'marco-ltda.firebasestorage.app',
    iosBundleId: 'com.lucatti.marcoLtda',
  );
}
